logging:
  level:
    ca.uhn.fhir: WARN
    com.zaxxer.hikari: WARN
    liquibase: INFO
    org.apache.camel: INFO
    org.ehrbase.client: WARN
    org.ehrbase.fhirbridge: INFO
    org.hibernate: INFO
    org.openehealth.ipf: ERROR
    org.quartz: WARN
    org.springframework: WARN
    org.springframework.boot: INFO
    org.apache.http: DEBUG # this has been added
